// ──────────────── Inline Styles ────────────────
export const styles = {
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    background: '#F5F6F8',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: 0,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: 500,
    color: 'var(--text)',
  },
  searchInput: {
    padding: '6px 12px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontFamily: 'var(--font)',
    color: 'var(--text)',
    background: 'var(--bg)',
    outline: 'none',
    width: 220,
    transition: 'border-color 0.15s',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  tabs: {
    display: 'flex',
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: 3,
    gap: 2,
    width: 'fit-content',
  },
  tabBtn: (active: boolean): React.CSSProperties => ({
    padding: '8px 20px',
    borderRadius: 'var(--radius-sm)',
    fontSize: 13,
    color: active ? '#fff' : 'var(--text-secondary)',
    cursor: 'pointer',
    border: 'none',
    background: active ? 'var(--primary)' : 'transparent',
    fontFamily: 'var(--font)',
    transition: 'all 0.15s',
    whiteSpace: 'nowrap',
    fontWeight: active ? 500 : 400,
  }),
  tabCount: (active: boolean): React.CSSProperties => ({
    display: 'inline-block',
    marginLeft: 6,
    padding: '0px 6px',
    borderRadius: 8,
    fontSize: 11,
    background: active ? 'rgba(255,255,255,0.2)' : 'var(--bg-input)',
    color: active ? '#fff' : 'var(--text-muted)',
  }),
  tableCard: {
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    overflow: 'hidden',
  },
  tableCardHeader: {
    padding: '14px 20px',
    borderBottom: '1px solid var(--primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: 'var(--primary)',
  },
  tableCardHeaderH3: {
    fontSize: 14,
    fontWeight: 600,
    color: '#fff',
  },
  tableCardHeaderCount: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
  },
  tableWrapper: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  } as React.CSSProperties,
  theadTh: {
    padding: '10px 16px',
    textAlign: 'left' as const,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.3px',
    background: 'var(--bg-card)',
    borderBottom: '1px solid var(--border)',
    whiteSpace: 'nowrap' as const,
  },
  theadThFirst: {
    padding: '10px 16px 10px 20px',
    textAlign: 'left' as const,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.3px',
    background: 'var(--bg-card)',
    borderBottom: '1px solid var(--border)',
    whiteSpace: 'nowrap' as const,
  },
  theadThLast: {
    padding: '10px 20px 10px 16px',
    textAlign: 'left' as const,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.3px',
    background: 'var(--bg-card)',
    borderBottom: '1px solid var(--border)',
    whiteSpace: 'nowrap' as const,
  },
  tbodyTd: {
    padding: '12px 16px',
    fontSize: 13,
    color: 'var(--text)',
    borderBottom: '1px solid var(--border-light)',
    verticalAlign: 'middle' as const,
  },
  tbodyTdFirst: {
    padding: '12px 16px 12px 20px',
    fontSize: 13,
    color: 'var(--text)',
    borderBottom: '1px solid var(--border-light)',
    verticalAlign: 'middle' as const,
  },
  tbodyTdLast: {
    padding: '12px 20px 12px 16px',
    fontSize: 13,
    color: 'var(--text)',
    borderBottom: '1px solid var(--border-light)',
    verticalAlign: 'middle' as const,
  },
  cellText: {
    maxWidth: 260,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    display: 'block',
  },
  cellMeta: {
    fontSize: 12,
    color: 'var(--text-muted)',
  },
  actionsCell: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap' as const,
  },
  statusBadge: (type: string): React.CSSProperties => {
    const base: React.CSSProperties = {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 4,
      padding: '2px 10px',
      borderRadius: 10,
      fontSize: 11,
      fontWeight: 500,
    };
    if (type === 'pending_review') return { ...base, background: 'rgba(251,188,4,0.1)', color: '#E37400' };
    if (type === 'published') return { ...base, background: 'rgba(52,168,83,0.1)', color: 'var(--success)' };
    if (type === 'rejected') return { ...base, background: 'rgba(234,67,53,0.1)', color: 'var(--danger)' };
    return base;
  },
  statusDot: (type: string): React.CSSProperties => ({
    width: 6,
    height: 6,
    borderRadius: '50%',
    display: 'inline-block',
    background: type === 'pending_review' ? '#E37400' : type === 'published' ? 'var(--success)' : 'var(--danger)',
  }),
  sourceTag: (type: string): React.CSSProperties => {
    const base: React.CSSProperties = {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 3,
      padding: '2px 8px',
      borderRadius: 4,
      fontSize: 11,
      fontWeight: 500,
    };
    if (type === 'auto_mined') return { ...base, background: 'rgba(66,133,244,0.08)', color: 'var(--info)' };
    return { ...base, background: 'rgba(38,50,56,0.06)', color: 'var(--text-secondary)' };
  },
  cacheTag: (active: boolean): React.CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 8px',
    borderRadius: 4,
    fontSize: 11,
    background: active ? 'rgba(52,168,83,0.08)' : 'rgba(154,160,166,0.08)',
    color: active ? 'var(--success)' : 'var(--text-muted)',
  }),
  pagination: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    borderTop: '1px solid var(--border)',
  },
  paginationInfo: {
    fontSize: 12,
    color: 'var(--text-muted)',
  },
  paginationBtns: {
    display: 'flex',
    gap: 4,
  },
  paginationBtn: (active?: boolean): React.CSSProperties => ({
    width: 32,
    height: 32,
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    background: active ? 'var(--primary)' : 'var(--bg)',
    cursor: active ? 'default' : 'pointer',
    fontSize: 13,
    color: active ? '#fff' : 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s',
    ...(active ? { borderColor: 'var(--primary)' } : {}),
  }),
  paginationEllipsis: {
    color: 'var(--text-muted)',
    padding: '0 4px',
    display: 'flex',
    alignItems: 'center',
    fontSize: 13,
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '48px 24px',
    color: 'var(--text-muted)',
  },
  emptyStateText: {
    fontSize: 14,
    marginTop: 8,
  },
  loadingState: {
    textAlign: 'center' as const,
    padding: '48px 24px',
    color: 'var(--text-muted)',
  },
  errorState: {
    textAlign: 'center' as const,
    padding: '48px 24px',
    color: 'var(--danger)',
  },
  errorRetryBtn: {
    marginTop: 12,
    padding: '6px 16px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    background: 'var(--bg)',
    cursor: 'pointer',
    fontSize: 13,
    color: 'var(--text)',
    fontFamily: 'var(--font)',
  },
  // Modal
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 1000,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    background: 'var(--bg)',
    borderRadius: 'var(--radius-lg)',
    boxShadow: 'var(--shadow-lg)',
    width: '90%',
    maxWidth: 640,
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column' as const,
    animation: 'fadeIn 0.15s',
  },
  modalHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalHeaderH3: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text)',
  },
  modalClose: {
    width: 28,
    height: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    cursor: 'pointer',
    color: 'var(--text-muted)',
    border: 'none',
    background: 'transparent',
    fontSize: 18,
    fontFamily: 'var(--font)',
  },
  modalBody: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: 20,
  },
  modalFooter: {
    padding: '12px 20px',
    borderTop: '1px solid var(--border)',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
  },
  formGroup: {
    marginBottom: 16,
  },
  formLabel: {
    display: 'block',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text)',
    marginBottom: 6,
  },
  formTextarea: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontFamily: 'var(--font)',
    fontSize: 13,
    color: 'var(--text)',
    outline: 'none',
    resize: 'vertical' as const,
    minHeight: 100,
    lineHeight: 1.6,
    background: 'var(--bg)',
    boxSizing: 'border-box' as const,
  },
  formInput: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontFamily: 'var(--font)',
    fontSize: 13,
    color: 'var(--text)',
    outline: 'none',
    background: 'var(--bg)',
    boxSizing: 'border-box' as const,
  },
  formReadonly: {
    fontSize: 14,
    color: 'var(--text)',
    fontWeight: 500,
    wordBreak: 'break-all' as const,
  },
  // Toast
  toast: (type: 'success' | 'error'): React.CSSProperties => ({
    position: 'fixed',
    top: 24,
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '10px 20px',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 500,
    zIndex: 1100,
    animation: 'slideDown 0.3s ease',
    background: type === 'success' ? '#E6F4EA' : '#FDECEA',
    color: type === 'success' ? 'var(--success)' : 'var(--danger)',
    border: type === 'success' ? '1px solid rgba(52,168,83,0.2)' : '1px solid rgba(234,67,53,0.2)',
  }),
  // Buttons
  btnGhost: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    border: 'none',
    transition: 'all 0.15s',
    fontFamily: 'var(--font)',
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    color: 'var(--text-secondary)',
  },
  btnOutlineXs: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 8px',
    borderRadius: 'var(--radius-sm)',
    fontSize: 11,
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border)',
    transition: 'all 0.15s',
    fontFamily: 'var(--font)',
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    color: 'var(--primary)',
  },
  btnDangerXs: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 8px',
    borderRadius: 'var(--radius-sm)',
    fontSize: 11,
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border)',
    transition: 'all 0.15s',
    fontFamily: 'var(--font)',
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    color: 'var(--danger)',
  },
  btnEditXs: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 8px',
    borderRadius: 'var(--radius-sm)',
    fontSize: 11,
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border)',
    transition: 'all 0.15s',
    fontFamily: 'var(--font)',
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    color: 'var(--info)',
  },
  btnSuccess: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    border: 'none',
    transition: 'all 0.15s',
    fontFamily: 'var(--font)',
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    background: 'var(--success)',
    color: '#fff',
  },
  btnDanger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border)',
    transition: 'all 0.15s',
    fontFamily: 'var(--font)',
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    color: 'var(--danger)',
  },
  relatedUnitLink: {
    color: 'var(--info)',
    cursor: 'pointer',
    maxWidth: 200,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    display: 'block',
  },
} as const;

// ──────────────── SVG Icons ────────────────
