// ===== Inline Style Constants =====
export const S = {
  // Content area
  content: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: 16,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 12,
    background: '#F5F6F8',
    height: '100%',
    minHeight: 0,
  },
  // Upload Zone
  uploadZone: {
    border: '2px dashed var(--border)',
    borderRadius: 'var(--radius-lg)',
    padding: '42px 24px',
    textAlign: 'center' as const,
    cursor: 'pointer',
    transition: 'all 0.15s',
    background: 'var(--bg)',
  },
  uploadZoneDragover: {
    borderColor: 'var(--primary)',
    background: 'var(--primary-light)',
  },
  uploadZoneIcon: {
    width: 32,
    height: 32,
    margin: '-4px auto 9px',
    color: 'var(--text-muted)',
  },
  uploadZoneH3: { fontSize: 14, fontWeight: 500, color: 'var(--text)', marginBottom: 2 },
  uploadZoneP: { fontSize: 12, color: 'var(--text-muted)' },
  uploadFormats: { marginTop: 6, display: 'flex', gap: 6, justifyContent: 'center', flexWrap: 'wrap' as const },
  formatTag: {
    padding: '2px 10px',
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    fontSize: 11,
    color: 'var(--text-secondary)',
  },
  // Import Bar
  importBar: {
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  importBarInfo: { flex: 1, minWidth: 0 },
  importBarName: { fontSize: 13, fontWeight: 500, color: 'var(--text)' },
  importBarFile: { fontSize: 11, color: 'var(--text-muted)', marginTop: 2 },
  importBarProgress: {
    flex: 1,
    maxWidth: 200,
    height: 6,
    background: 'var(--bg-input)',
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  importBarProgressFill: {
    height: '100%',
    background: 'var(--primary)',
    borderRadius: 3,
    transition: 'width 0.3s',
  },
  importBarPct: { fontSize: 12, color: 'var(--text-secondary)', minWidth: 36, textAlign: 'right' as const },
  importBarStatus: (status: string) => ({
    fontSize: 12,
    fontWeight: 500,
    color: status === 'completed' ? 'var(--success)' : status === 'failed' ? 'var(--danger)' : 'var(--info)',
  }),
  importBarClose: {
    cursor: 'pointer',
    color: 'var(--text-muted)',
    padding: 4,
    borderRadius: 4,
    display: 'flex',
    alignItems: 'center',
  },
  // Toolbar
  toolbar: { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' as const },
  searchBox: { position: 'relative' as const, flex: 1, minWidth: 200, maxWidth: 360 },
  searchInput: {
    width: '100%',
    padding: '8px 12px 8px 34px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontFamily: 'var(--font)',
    fontSize: 13,
    color: 'var(--text)',
    background: 'var(--bg)',
    outline: 'none',
    transition: 'border-color 0.15s',
    lineHeight: '20px',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: 10,
    top: '50%',
    transform: 'translateY(-50%)',
    color: 'var(--text-muted)',
    pointerEvents: 'none' as const,
  },
  filterSelect: {
    padding: '8px 12px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontFamily: 'var(--font)',
    fontSize: 13,
    color: 'var(--text)',
    background: 'var(--bg)',
    outline: 'none',
    cursor: 'pointer',
    minWidth: 120,
  },
  toolbarSpacer: { flex: 1 },
  selectedCount: { fontSize: 12, color: 'var(--text-muted)' },
  // Table Card
  tableCard: {
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    overflow: 'hidden' as const,
  },
  tableCardHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid var(--primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: 'var(--primary)',
  },
  tableCardHeaderH3: { fontSize: 14, fontWeight: 600, color: '#fff' },
  tableCardHeaderCount: { fontSize: 12, color: 'rgba(255,255,255,0.7)' },
  tableWrapper: { overflowX: 'auto' as const },
  table: { width: '100%', borderCollapse: 'collapse' as const },
  th: {
    padding: '10px 16px',
    textAlign: 'left' as const,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.3,
    background: 'var(--bg-card)',
    borderBottom: '1px solid var(--border)',
    whiteSpace: 'nowrap' as const,
  },
  thFirst: { paddingLeft: 20 },
  thLast: { paddingRight: 20 },
  td: {
    padding: '12px 16px',
    fontSize: 13,
    color: 'var(--text)',
    borderBottom: '1px solid var(--border-light)',
    verticalAlign: 'middle' as const,
  },
  tdFirst: { paddingLeft: 20 },
  tdLast: { paddingRight: 20 },
  rowHover: { background: 'var(--bg-hover)' },
  rowCheckbox: { width: 16, height: 16, accentColor: 'var(--primary)', cursor: 'pointer' },
  cellTitle: {
    fontWeight: 500,
    color: 'var(--text)',
    cursor: 'pointer',
    maxWidth: 280,
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis' as const,
    whiteSpace: 'nowrap' as const,
  },
  cellMeta: { fontSize: 12, color: 'var(--text-muted)' },
  fileTypeTag: {
    padding: '2px 8px',
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 4,
    fontSize: 11,
    color: 'var(--text-secondary)',
    fontFamily: 'monospace',
  },
  actionsCell: { display: 'flex', gap: 4 },
  // Status Badge
  statusBadge: (status: string) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '2px 10px',
    borderRadius: 10,
    fontSize: 11,
    fontWeight: 500,
    background: status === 'published' ? 'rgba(52,168,83,0.1)' : status === 'draft' ? 'rgba(251,188,4,0.1)' : 'rgba(234,67,53,0.1)',
    color: status === 'published' ? 'var(--success)' : status === 'draft' ? '#E37400' : 'var(--danger)',
  }),
  statusDot: (status: string) => ({
    width: 6,
    height: 6,
    borderRadius: '50%',
    display: 'inline-block',
    background: status === 'published' ? 'var(--success)' : status === 'draft' ? '#E37400' : 'var(--danger)',
  }),
  // Empty State
  emptyState: {
    textAlign: 'center' as const,
    padding: '48px 24px',
    color: 'var(--text-muted)',
  },
  emptyStateP: { fontSize: 14 },
  // Pagination
  pagination: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    borderTop: '1px solid var(--border)',
  },
  paginationInfo: { fontSize: 12, color: 'var(--text-muted)' },
  paginationBtns: { display: 'flex', gap: 4 },
  pageBtn: (active: boolean) => ({
    width: 32,
    height: 32,
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    background: active ? 'var(--primary)' : 'var(--bg)',
    color: active ? '#fff' : 'var(--text-secondary)',
    cursor: active ? 'default' : 'pointer',
    fontSize: 13,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s',
    borderColor: active ? 'var(--primary)' : 'var(--border)',
  }),
  pageBtnDisabled: {
    width: 32,
    height: 32,
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    background: 'var(--bg)',
    cursor: 'not-allowed',
    fontSize: 13,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-placeholder)',
  },
  pageEllipsis: { color: 'var(--text-muted)', padding: '0 4px', display: 'flex', alignItems: 'center' },
  // Trash
  trashRestoreBtn: {
    padding: '4px 14px',
    fontSize: 12,
    borderRadius: 4,
    cursor: 'pointer',
    border: '1px solid var(--success)',
    background: 'rgba(52,168,83,0.08)',
    color: 'var(--success)',
    fontWeight: 500,
  },
  trashDeleteBtn: {
    padding: '4px 14px',
    fontSize: 12,
    borderRadius: 4,
    cursor: 'pointer',
    border: '1px solid var(--danger)',
    background: 'rgba(234,67,53,0.08)',
    color: 'var(--danger)',
    fontWeight: 500,
  },
  loading: {
    textAlign: 'center' as const,
    padding: '48px 24px',
    color: 'var(--text-muted)',
    fontSize: 14,
  },
  // Modal
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 1000,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    background: 'var(--bg)',
    borderRadius: 'var(--radius-lg)',
    boxShadow: 'var(--shadow-lg)',
    width: '90%',
    maxWidth: 720,
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column' as const,
    animation: 'fadeIn 0.15s',
  },
  modalHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalHeaderH3: { fontSize: 15, fontWeight: 600 },
  modalClose: {
    width: 28,
    height: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    cursor: 'pointer',
    color: 'var(--text-muted)',
    border: 'none',
    background: 'transparent',
    fontSize: 18,
  },
  modalBody: { flex: 1, overflowY: 'auto' as const, padding: 20 },
  modalFooter: {
    padding: '12px 20px',
    borderTop: '1px solid var(--border)',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
  },
  // Detail
  detailSection: { marginBottom: 20 },
  detailLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.3,
    marginBottom: 6,
  },
  detailValue: { fontSize: 14, color: 'var(--text)', lineHeight: 1.7 },
  detailMetaGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 },
  // Form
  formGroup: { marginBottom: 16 },
  formLabel: { display: 'block', fontSize: 13, fontWeight: 500, color: 'var(--text)', marginBottom: 6 },
  formInput: {
    width: '100%',
    padding: '8px 12px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontFamily: 'var(--font)',
    fontSize: 13,
    color: 'var(--text)',
    outline: 'none',
    transition: 'border-color 0.15s',
    background: 'var(--bg)',
  },
  formTextarea: {
    width: '100%',
    padding: '8px 12px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    fontFamily: 'var(--font)',
    fontSize: 13,
    color: 'var(--text)',
    outline: 'none',
    transition: 'border-color 0.15s',
    background: 'var(--bg)',
    resize: 'vertical' as const,
    minHeight: 120,
    lineHeight: 1.6,
  },
  // Permissions
  permSection: { marginTop: 20, paddingTop: 20, borderTop: '1px solid var(--border)' },
  permList: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  permItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    background: 'var(--bg-card)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 13,
  },
  permType: { fontWeight: 500, color: 'var(--primary)', minWidth: 60 },
  permId: { color: 'var(--text-secondary)' },
  permRemove: { cursor: 'pointer', color: 'var(--text-muted)', padding: '2px 6px', borderRadius: 4 },
  permAdd: { display: 'flex', gap: 8, marginTop: 8 },
  permAddSelect: {
    padding: '6px 10px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 13,
    fontFamily: 'var(--font)',
    background: 'var(--bg)',
    outline: 'none',
    minWidth: 100,
  },
  permAddInput: {
    flex: 1,
    padding: '6px 10px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 13,
    fontFamily: 'var(--font)',
    outline: 'none',
  },
  // Toast
  toast: {
    position: 'fixed' as const,
    top: 24,
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '10px 20px',
    borderRadius: 'var(--radius)',
    fontSize: 13,
    fontWeight: 500,
    zIndex: 2000,
    animation: 'slideDown 0.3s ease',
  },
  toastSuccess: { background: '#E6F4EA', color: 'var(--success)', border: '1px solid rgba(52,168,83,0.2)' },
  toastError: { background: '#FDECEA', color: 'var(--danger)', border: '1px solid rgba(234,67,53,0.2)' },
}

// ===== SVG Icons =====

